/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  IsOptional,
  MaxLength,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { University } from "../../university/base/University";
import { Recommendation } from "../../recommendation/base/Recommendation";
import { EnumStudentRoles } from "./EnumStudentRoles";
import { EnumStudentPermissions } from "./EnumStudentPermissions";

@ObjectType()
class Student {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password!: string | null;

  @ApiProperty({
    required: false,
    type: () => University,
  })
  @ValidateNested()
  @Type(() => University)
  @IsOptional()
  university?: University | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Recommendation],
  })
  @ValidateNested()
  @Type(() => Recommendation)
  @IsOptional()
  recommendations?: Array<Recommendation>;

  @ApiProperty({
    required: false,
    enum: EnumStudentRoles,
    isArray: true,
  })
  @IsEnum(EnumStudentRoles, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumStudentRoles], {
    nullable: true,
  })
  roles?: Array<"Option1">;

  @ApiProperty({
    required: false,
    enum: EnumStudentPermissions,
    isArray: true,
  })
  @IsEnum(EnumStudentPermissions, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumStudentPermissions], {
    nullable: true,
  })
  permissions?: Array<"Option1">;
}

export { Student as Student };
