/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VideoCallService } from "../videoCall.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VideoCallCreateInput } from "./VideoCallCreateInput";
import { VideoCall } from "./VideoCall";
import { Post } from "../../post/base/Post";
import { VideoCallFindManyArgs } from "./VideoCallFindManyArgs";
import { VideoCallWhereUniqueInput } from "./VideoCallWhereUniqueInput";
import { VideoCallUpdateInput } from "./VideoCallUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VideoCallControllerBase {
  constructor(
    protected readonly service: VideoCallService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VideoCall })
  @nestAccessControl.UseRoles({
    resource: "VideoCall",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVideoCall(
    @common.Body() data: VideoCallCreateInput
  ): Promise<VideoCall> {
    return await this.service.createVideoCall({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        callEnd: true,
        callStart: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VideoCall] })
  @ApiNestedQuery(VideoCallFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VideoCall",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async videoCalls(@common.Req() request: Request): Promise<VideoCall[]> {
    const args = plainToClass(VideoCallFindManyArgs, request.query);
    return this.service.videoCalls({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        callEnd: true,
        callStart: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VideoCall })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoCall",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async videoCall(
    @common.Param() params: VideoCallWhereUniqueInput
  ): Promise<VideoCall | null> {
    const result = await this.service.videoCall({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        callEnd: true,
        callStart: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VideoCall })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoCall",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVideoCall(
    @common.Param() params: VideoCallWhereUniqueInput,
    @common.Body() data: VideoCallUpdateInput
  ): Promise<VideoCall | null> {
    try {
      return await this.service.updateVideoCall({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          callEnd: true,
          callStart: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VideoCall })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoCall",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVideoCall(
    @common.Param() params: VideoCallWhereUniqueInput
  ): Promise<VideoCall | null> {
    try {
      return await this.service.deleteVideoCall({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          callEnd: true,
          callStart: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
