/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UniversityService } from "../university.service";
import { UniversityCreateInput } from "./UniversityCreateInput";
import { University } from "./University";
import { Post } from "../../post/base/Post";
import { UniversityFindManyArgs } from "./UniversityFindManyArgs";
import { UniversityWhereUniqueInput } from "./UniversityWhereUniqueInput";
import { UniversityUpdateInput } from "./UniversityUpdateInput";
import { StudentFindManyArgs } from "../../student/base/StudentFindManyArgs";
import { Student } from "../../student/base/Student";
import { StudentWhereUniqueInput } from "../../student/base/StudentWhereUniqueInput";

export class UniversityControllerBase {
  constructor(protected readonly service: UniversityService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: University })
  async createUniversity(
    @common.Body() data: UniversityCreateInput
  ): Promise<University> {
    return await this.service.createUniversity({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        location: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [University] })
  @ApiNestedQuery(UniversityFindManyArgs)
  async universities(@common.Req() request: Request): Promise<University[]> {
    const args = plainToClass(UniversityFindManyArgs, request.query);
    return this.service.universities({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        location: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: University })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async university(
    @common.Param() params: UniversityWhereUniqueInput
  ): Promise<University | null> {
    const result = await this.service.university({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        location: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: University })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUniversity(
    @common.Param() params: UniversityWhereUniqueInput,
    @common.Body() data: UniversityUpdateInput
  ): Promise<University | null> {
    try {
      return await this.service.updateUniversity({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          location: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: University })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUniversity(
    @common.Param() params: UniversityWhereUniqueInput
  ): Promise<University | null> {
    try {
      return await this.service.deleteUniversity({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          location: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/students")
  @ApiNestedQuery(StudentFindManyArgs)
  async findStudents(
    @common.Req() request: Request,
    @common.Param() params: UniversityWhereUniqueInput
  ): Promise<Student[]> {
    const query = plainToClass(StudentFindManyArgs, request.query);
    const results = await this.service.findStudents(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        email: true,
        password: true,

        university: {
          select: {
            id: true,
          },
        },

        location: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/students")
  async connectStudents(
    @common.Param() params: UniversityWhereUniqueInput,
    @common.Body() body: StudentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      students: {
        connect: body,
      },
    };
    await this.service.updateUniversity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/students")
  async updateStudents(
    @common.Param() params: UniversityWhereUniqueInput,
    @common.Body() body: StudentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      students: {
        set: body,
      },
    };
    await this.service.updateUniversity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/students")
  async disconnectStudents(
    @common.Param() params: UniversityWhereUniqueInput,
    @common.Body() body: StudentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      students: {
        disconnect: body,
      },
    };
    await this.service.updateUniversity({
      where: params,
      data,
      select: { id: true },
    });
  }
}
