/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AccommodationProviderService } from "../accommodationProvider.service";
import { AccommodationProviderCreateInput } from "./AccommodationProviderCreateInput";
import { AccommodationProvider } from "./AccommodationProvider";
import { Post } from "../../post/base/Post";
import { AccommodationProviderFindManyArgs } from "./AccommodationProviderFindManyArgs";
import { AccommodationProviderWhereUniqueInput } from "./AccommodationProviderWhereUniqueInput";
import { AccommodationProviderUpdateInput } from "./AccommodationProviderUpdateInput";

export class AccommodationProviderControllerBase {
  constructor(protected readonly service: AccommodationProviderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AccommodationProvider })
  async createAccommodationProvider(
    @common.Body() data: AccommodationProviderCreateInput
  ): Promise<AccommodationProvider> {
    return await this.service.createAccommodationProvider({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        email: true,
        password: true,
        roomType: true,
        location: true,
        electricityIncluded: true,
        waterIncluded: true,
        price: true,
        name: true,
        popularity: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AccommodationProvider] })
  @ApiNestedQuery(AccommodationProviderFindManyArgs)
  async accommodationProviders(
    @common.Req() request: Request
  ): Promise<AccommodationProvider[]> {
    const args = plainToClass(AccommodationProviderFindManyArgs, request.query);
    return this.service.accommodationProviders({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        email: true,
        password: true,
        roomType: true,
        location: true,
        electricityIncluded: true,
        waterIncluded: true,
        price: true,
        name: true,
        popularity: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AccommodationProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async accommodationProvider(
    @common.Param() params: AccommodationProviderWhereUniqueInput
  ): Promise<AccommodationProvider | null> {
    const result = await this.service.accommodationProvider({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        email: true,
        password: true,
        roomType: true,
        location: true,
        electricityIncluded: true,
        waterIncluded: true,
        price: true,
        name: true,
        popularity: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AccommodationProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAccommodationProvider(
    @common.Param() params: AccommodationProviderWhereUniqueInput,
    @common.Body() data: AccommodationProviderUpdateInput
  ): Promise<AccommodationProvider | null> {
    try {
      return await this.service.updateAccommodationProvider({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          email: true,
          password: true,
          roomType: true,
          location: true,
          electricityIncluded: true,
          waterIncluded: true,
          price: true,
          name: true,
          popularity: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AccommodationProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAccommodationProvider(
    @common.Param() params: AccommodationProviderWhereUniqueInput
  ): Promise<AccommodationProvider | null> {
    try {
      return await this.service.deleteAccommodationProvider({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          email: true,
          password: true,
          roomType: true,
          location: true,
          electricityIncluded: true,
          waterIncluded: true,
          price: true,
          name: true,
          popularity: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
